server.port=8080

spring.application.name=vanitha-coverings

# Datasource Setup (Dynamic Environment Variables with local default)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/vanitha_coverings?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:@Sanjai10}

# JPA and Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Multipart config for images upload
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
logging.level.org.hibernate.SQL=WARN
logging.level.com.vanitha=INFO
